# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/daniel/GitHub/multitable/./gui/finalizer.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FinalizerWindow(object):
    def setupUi(self, FinalizerWindow):
        FinalizerWindow.setObjectName("FinalizerWindow")
        FinalizerWindow.resize(857, 521)
        self.Mainwidget = QtWidgets.QWidget(FinalizerWindow)
        self.Mainwidget.setObjectName("Mainwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.Mainwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.CifFileGroupBox = QtWidgets.QGroupBox(self.Mainwidget)
        self.CifFileGroupBox.setObjectName("CifFileGroupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.CifFileGroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.CifFileGroupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.CifFileGroupBox)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.CifFileGroupBox, 0, 0, 1, 1)
        self.TemplatesGroupBox = QtWidgets.QGroupBox(self.Mainwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.TemplatesGroupBox.sizePolicy().hasHeightForWidth())
        self.TemplatesGroupBox.setSizePolicy(sizePolicy)
        self.TemplatesGroupBox.setObjectName("TemplatesGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.TemplatesGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.EditTemplateButton = QtWidgets.QPushButton(self.TemplatesGroupBox)
        self.EditTemplateButton.setObjectName("EditTemplateButton")
        self.gridLayout_2.addWidget(self.EditTemplateButton, 1, 1, 1, 1)
        self.TemplatesListWidget = QtWidgets.QListWidget(self.TemplatesGroupBox)
        self.TemplatesListWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.TemplatesListWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TemplatesListWidget.setObjectName("TemplatesListWidget")
        item = QtWidgets.QListWidgetItem()
        self.TemplatesListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.TemplatesListWidget.addItem(item)
        self.gridLayout_2.addWidget(self.TemplatesListWidget, 0, 0, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.TemplatesGroupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.TemplatesGroupBox, 1, 0, 1, 1)
        self.DataFilesGroupBox = QtWidgets.QGroupBox(self.Mainwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.DataFilesGroupBox.sizePolicy().hasHeightForWidth())
        self.DataFilesGroupBox.setSizePolicy(sizePolicy)
        self.DataFilesGroupBox.setObjectName("DataFilesGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.DataFilesGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.SaintLstFileButton = QtWidgets.QPushButton(self.DataFilesGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaintLstFileButton.sizePolicy().hasHeightForWidth())
        self.SaintLstFileButton.setSizePolicy(sizePolicy)
        self.SaintLstFileButton.setObjectName("SaintLstFileButton")
        self.gridLayout_3.addWidget(self.SaintLstFileButton, 0, 1, 1, 1)
        self.SaintLstFileEdit = QtWidgets.QLineEdit(self.DataFilesGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaintLstFileEdit.sizePolicy().hasHeightForWidth())
        self.SaintLstFileEdit.setSizePolicy(sizePolicy)
        self.SaintLstFileEdit.setObjectName("SaintLstFileEdit")
        self.gridLayout_3.addWidget(self.SaintLstFileEdit, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.DataFilesGroupBox, 2, 0, 1, 1)
        self.CifDataItemsGroupBox = QtWidgets.QGroupBox(self.Mainwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CifDataItemsGroupBox.sizePolicy().hasHeightForWidth())
        self.CifDataItemsGroupBox.setSizePolicy(sizePolicy)
        self.CifDataItemsGroupBox.setObjectName("CifDataItemsGroupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.CifDataItemsGroupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.CifItemsTable = QtWidgets.QTableWidget(self.CifDataItemsGroupBox)
        self.CifItemsTable.setStyleSheet("font: 13pt \".SF NS Text\";\n"
"")
        self.CifItemsTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CifItemsTable.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.CifItemsTable.setAlternatingRowColors(True)
        self.CifItemsTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.CifItemsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.CifItemsTable.setShowGrid(True)
        self.CifItemsTable.setWordWrap(False)
        self.CifItemsTable.setObjectName("CifItemsTable")
        self.CifItemsTable.setColumnCount(2)
        self.CifItemsTable.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.CifItemsTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setItem(2, 1, item)
        self.CifItemsTable.horizontalHeader().setCascadingSectionResizes(True)
        self.CifItemsTable.horizontalHeader().setDefaultSectionSize(200)
        self.CifItemsTable.horizontalHeader().setStretchLastSection(True)
        self.CifItemsTable.verticalHeader().setDefaultSectionSize(23)
        self.CifItemsTable.verticalHeader().setMinimumSectionSize(20)
        self.CifItemsTable.verticalHeader().setStretchLastSection(False)
        self.gridLayout_5.addWidget(self.CifItemsTable, 0, 0, 1, 3)
        self.SaveCifButton = QtWidgets.QPushButton(self.CifDataItemsGroupBox)
        self.SaveCifButton.setObjectName("SaveCifButton")
        self.gridLayout_5.addWidget(self.SaveCifButton, 1, 0, 1, 1)
        self.SaveResidualsTableButton = QtWidgets.QPushButton(self.CifDataItemsGroupBox)
        self.SaveResidualsTableButton.setObjectName("SaveResidualsTableButton")
        self.gridLayout_5.addWidget(self.SaveResidualsTableButton, 1, 1, 1, 1)
        self.SaveFullReportButton = QtWidgets.QPushButton(self.CifDataItemsGroupBox)
        self.SaveFullReportButton.setObjectName("SaveFullReportButton")
        self.gridLayout_5.addWidget(self.SaveFullReportButton, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.CifDataItemsGroupBox, 0, 1, 3, 1)
        FinalizerWindow.setCentralWidget(self.Mainwidget)
        self.actionSave_Report = QtWidgets.QAction(FinalizerWindow)
        self.actionSave_Report.setObjectName("actionSave_Report")
        self.actionSave_CIF_File = QtWidgets.QAction(FinalizerWindow)
        self.actionSave_CIF_File.setObjectName("actionSave_CIF_File")
        self.actionedit_templates = QtWidgets.QAction(FinalizerWindow)
        self.actionedit_templates.setObjectName("actionedit_templates")

        self.retranslateUi(FinalizerWindow)
        QtCore.QMetaObject.connectSlotsByName(FinalizerWindow)

    def retranslateUi(self, FinalizerWindow):
        _translate = QtCore.QCoreApplication.translate
        FinalizerWindow.setWindowTitle(_translate("FinalizerWindow", "Mutitable"))
        self.CifFileGroupBox.setTitle(_translate("FinalizerWindow", "Cif file"))
        self.pushButton.setText(_translate("FinalizerWindow", "Select File"))
        self.TemplatesGroupBox.setTitle(_translate("FinalizerWindow", "Templates"))
        self.EditTemplateButton.setText(_translate("FinalizerWindow", "Edit Template"))
        __sortingEnabled = self.TemplatesListWidget.isSortingEnabled()
        self.TemplatesListWidget.setSortingEnabled(False)
        item = self.TemplatesListWidget.item(0)
        item.setText(_translate("FinalizerWindow", "Bruker D8 VENTURE"))
        item = self.TemplatesListWidget.item(1)
        item.setText(_translate("FinalizerWindow", "Bruker SMART APEXII QUAZAR"))
        self.TemplatesListWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_2.setText(_translate("FinalizerWindow", "New Template"))
        self.DataFilesGroupBox.setTitle(_translate("FinalizerWindow", "Data Files"))
        self.SaintLstFileButton.setText(_translate("FinalizerWindow", "PushButton"))
        self.SaintLstFileEdit.setText(_translate("FinalizerWindow", "Data files appear here, depending on the selection in cif items table"))
        self.CifDataItemsGroupBox.setTitle(_translate("FinalizerWindow", "Missing CIF Items"))
        item = self.CifItemsTable.verticalHeaderItem(0)
        item.setText(_translate("FinalizerWindow", "_ls_refine_foo_bar"))
        item = self.CifItemsTable.verticalHeaderItem(1)
        item.setText(_translate("FinalizerWindow", "_foo_foo_bar"))
        item = self.CifItemsTable.verticalHeaderItem(2)
        item.setText(_translate("FinalizerWindow", "_fantasy_cif_keyword"))
        item = self.CifItemsTable.horizontalHeaderItem(0)
        item.setText(_translate("FinalizerWindow", "CIF data"))
        item = self.CifItemsTable.horizontalHeaderItem(1)
        item.setText(_translate("FinalizerWindow", "own data"))
        __sortingEnabled = self.CifItemsTable.isSortingEnabled()
        self.CifItemsTable.setSortingEnabled(False)
        item = self.CifItemsTable.item(0, 0)
        item.setText(_translate("FinalizerWindow", "?"))
        item = self.CifItemsTable.item(0, 1)
        item.setText(_translate("FinalizerWindow", "125"))
        item = self.CifItemsTable.item(1, 0)
        item.setText(_translate("FinalizerWindow", "10.4"))
        item = self.CifItemsTable.item(1, 1)
        item.setText(_translate("FinalizerWindow", "12.6"))
        item = self.CifItemsTable.item(2, 0)
        item.setText(_translate("FinalizerWindow", "?"))
        item = self.CifItemsTable.item(2, 1)
        item.setText(_translate("FinalizerWindow", "highlight filed that should be used"))
        self.CifItemsTable.setSortingEnabled(__sortingEnabled)
        self.SaveCifButton.setText(_translate("FinalizerWindow", "Save Cif File"))
        self.SaveResidualsTableButton.setText(_translate("FinalizerWindow", "Save Residuals Table"))
        self.SaveFullReportButton.setText(_translate("FinalizerWindow", "Save Full Report"))
        self.actionSave_Report.setText(_translate("FinalizerWindow", "Save Report"))
        self.actionSave_CIF_File.setText(_translate("FinalizerWindow", "Save CIF File"))
        self.actionedit_templates.setText(_translate("FinalizerWindow", "edit templates"))


