# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/daniel/GitHub/multitable/./gui/finalizer.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MultitableWindow(object):
    def setupUi(self, MultitableWindow):
        MultitableWindow.setObjectName("MultitableWindow")
        MultitableWindow.resize(1151, 669)
        self.Mainwidget = QtWidgets.QWidget(MultitableWindow)
        self.Mainwidget.setObjectName("Mainwidget")
        self.MainTabWidget = QtWidgets.QTabWidget(self.Mainwidget)
        self.MainTabWidget.setGeometry(QtCore.QRect(350, 10, 791, 621))
        self.MainTabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.MainTabWidget.setObjectName("MainTabWidget")
        self.SelectFilesTab = QtWidgets.QWidget()
        self.SelectFilesTab.setObjectName("SelectFilesTab")
        self.MainTabWidget.addTab(self.SelectFilesTab, "")
        self.SelectDataTab = QtWidgets.QWidget()
        self.SelectDataTab.setObjectName("SelectDataTab")
        self.tableWidget = QtWidgets.QTableWidget(self.SelectDataTab)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 741, 561))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        self.MainTabWidget.addTab(self.SelectDataTab, "")
        self.WriteFilesTab = QtWidgets.QWidget()
        self.WriteFilesTab.setObjectName("WriteFilesTab")
        self.MainTabWidget.addTab(self.WriteFilesTab, "")
        self.groupBox = QtWidgets.QGroupBox(self.Mainwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 311, 61))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.groupBox_2 = QtWidgets.QGroupBox(self.Mainwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 70, 321, 211))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.groupBox_2)
        self.treeWidget_2.setObjectName("treeWidget_2")
        self.verticalLayout_2.addWidget(self.treeWidget_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.Mainwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 580, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.Mainwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 580, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.Mainwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(210, 580, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        MultitableWindow.setCentralWidget(self.Mainwidget)
        self.menuBar = QtWidgets.QMenuBar(MultitableWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1151, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuoptions = QtWidgets.QMenu(self.menuBar)
        self.menuoptions.setObjectName("menuoptions")
        MultitableWindow.setMenuBar(self.menuBar)
        self.actionSave_Report = QtWidgets.QAction(MultitableWindow)
        self.actionSave_Report.setObjectName("actionSave_Report")
        self.actionSave_CIF_File = QtWidgets.QAction(MultitableWindow)
        self.actionSave_CIF_File.setObjectName("actionSave_CIF_File")
        self.actionedit_templates = QtWidgets.QAction(MultitableWindow)
        self.actionedit_templates.setObjectName("actionedit_templates")
        self.menuFile.addAction(self.actionSave_Report)
        self.menuFile.addAction(self.actionSave_CIF_File)
        self.menuoptions.addAction(self.actionedit_templates)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuoptions.menuAction())

        self.retranslateUi(MultitableWindow)
        self.MainTabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MultitableWindow)

    def retranslateUi(self, MultitableWindow):
        _translate = QtCore.QCoreApplication.translate
        MultitableWindow.setWindowTitle(_translate("MultitableWindow", "Mutitable"))
        self.MainTabWidget.setTabText(self.MainTabWidget.indexOf(self.SelectFilesTab), _translate("MultitableWindow", "Select Files"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MultitableWindow", "_ls_refine_foo_bar"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MultitableWindow", "_WR_foo"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MultitableWindow", "dsrgdg"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MultitableWindow", "CIF data"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MultitableWindow", "own data"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MultitableWindow", "?"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MultitableWindow", "125"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MultitableWindow", "10.4"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MultitableWindow", "12.6"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MultitableWindow", "highlight filed that should be used"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.MainTabWidget.setTabText(self.MainTabWidget.indexOf(self.SelectDataTab), _translate("MultitableWindow", "Select Data"))
        self.MainTabWidget.setTabText(self.MainTabWidget.indexOf(self.WriteFilesTab), _translate("MultitableWindow", "Write Files"))
        self.groupBox.setTitle(_translate("MultitableWindow", "Cif file"))
        self.pushButton.setText(_translate("MultitableWindow", "Select File"))
        self.groupBox_2.setTitle(_translate("MultitableWindow", "Templates"))
        self.treeWidget_2.headerItem().setText(0, _translate("MultitableWindow", "list of available templates here..."))
        self.pushButton_2.setText(_translate("MultitableWindow", "Save Cif File"))
        self.pushButton_3.setText(_translate("MultitableWindow", "Save Report"))
        self.pushButton_4.setText(_translate("MultitableWindow", "Save Tables"))
        self.menuFile.setTitle(_translate("MultitableWindow", "File"))
        self.menuoptions.setTitle(_translate("MultitableWindow", "options"))
        self.actionSave_Report.setText(_translate("MultitableWindow", "Save Report"))
        self.actionSave_CIF_File.setText(_translate("MultitableWindow", "Save CIF File"))
        self.actionedit_templates.setText(_translate("MultitableWindow", "edit templates"))


