# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/daniel/GitHub/multitable/./gui/finalizer.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FinalizerWindow(object):
    def setupUi(self, FinalizerWindow):
        FinalizerWindow.setObjectName("FinalizerWindow")
        FinalizerWindow.resize(857, 521)
        self.Mainwidget = QtWidgets.QWidget(FinalizerWindow)
        self.Mainwidget.setObjectName("Mainwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.Mainwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.Mainwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.TemplatesGroupBox = QtWidgets.QGroupBox(self.Mainwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TemplatesGroupBox.sizePolicy().hasHeightForWidth())
        self.TemplatesGroupBox.setSizePolicy(sizePolicy)
        self.TemplatesGroupBox.setObjectName("TemplatesGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.TemplatesGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.TemplatesGroupBox)
        self.treeWidget_2.setObjectName("treeWidget_2")
        self.verticalLayout_2.addWidget(self.treeWidget_2)
        self.pushButton_8 = QtWidgets.QPushButton(self.TemplatesGroupBox)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_2.addWidget(self.pushButton_8)
        self.gridLayout.addWidget(self.TemplatesGroupBox, 1, 0, 1, 1)
        self.DataFilesGroupBox = QtWidgets.QGroupBox(self.Mainwidget)
        self.DataFilesGroupBox.setObjectName("DataFilesGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.DataFilesGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.DataFilesGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_3.addWidget(self.pushButton_7, 0, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.DataFilesGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.DataFilesGroupBox, 2, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.Mainwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(25)
        self.gridLayout_5.addWidget(self.tableWidget, 0, 0, 1, 3)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_5.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_5.addWidget(self.pushButton_4, 1, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_5.addWidget(self.pushButton_3, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 0, 1, 3, 1)
        FinalizerWindow.setCentralWidget(self.Mainwidget)
        self.menuBar = QtWidgets.QMenuBar(FinalizerWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 857, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuoptions = QtWidgets.QMenu(self.menuBar)
        self.menuoptions.setObjectName("menuoptions")
        FinalizerWindow.setMenuBar(self.menuBar)
        self.actionSave_Report = QtWidgets.QAction(FinalizerWindow)
        self.actionSave_Report.setObjectName("actionSave_Report")
        self.actionSave_CIF_File = QtWidgets.QAction(FinalizerWindow)
        self.actionSave_CIF_File.setObjectName("actionSave_CIF_File")
        self.actionedit_templates = QtWidgets.QAction(FinalizerWindow)
        self.actionedit_templates.setObjectName("actionedit_templates")
        self.menuFile.addAction(self.actionSave_Report)
        self.menuFile.addAction(self.actionSave_CIF_File)
        self.menuoptions.addAction(self.actionedit_templates)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuoptions.menuAction())

        self.retranslateUi(FinalizerWindow)
        QtCore.QMetaObject.connectSlotsByName(FinalizerWindow)

    def retranslateUi(self, FinalizerWindow):
        _translate = QtCore.QCoreApplication.translate
        FinalizerWindow.setWindowTitle(_translate("FinalizerWindow", "Mutitable"))
        self.groupBox.setTitle(_translate("FinalizerWindow", "Cif file"))
        self.pushButton.setText(_translate("FinalizerWindow", "Select File"))
        self.TemplatesGroupBox.setTitle(_translate("FinalizerWindow", "Templates"))
        self.treeWidget_2.headerItem().setText(0, _translate("FinalizerWindow", "list of available templates here..."))
        self.pushButton_8.setText(_translate("FinalizerWindow", "Edit Template"))
        self.DataFilesGroupBox.setTitle(_translate("FinalizerWindow", "Data Files"))
        self.pushButton_7.setText(_translate("FinalizerWindow", "PushButton"))
        self.groupBox_3.setTitle(_translate("FinalizerWindow", "Missing CIF Items"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("FinalizerWindow", "_ls_refine_foo_bar"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("FinalizerWindow", "_WR_foo"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("FinalizerWindow", "dsrgdg"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("FinalizerWindow", "CIF data"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("FinalizerWindow", "own data"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("FinalizerWindow", "?"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("FinalizerWindow", "125"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("FinalizerWindow", "10.4"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("FinalizerWindow", "12.6"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("FinalizerWindow", "highlight filed that should be used"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_2.setText(_translate("FinalizerWindow", "Save Cif File"))
        self.pushButton_4.setText(_translate("FinalizerWindow", "Save Residuals Table"))
        self.pushButton_3.setText(_translate("FinalizerWindow", "Save Full Report"))
        self.menuFile.setTitle(_translate("FinalizerWindow", "File"))
        self.menuoptions.setTitle(_translate("FinalizerWindow", "options"))
        self.actionSave_Report.setText(_translate("FinalizerWindow", "Save Report"))
        self.actionSave_CIF_File.setText(_translate("FinalizerWindow", "Save CIF File"))
        self.actionedit_templates.setText(_translate("FinalizerWindow", "edit templates"))


